[tox]
envlist = py310

[testenv]
deps =
    pytest
    pytest-mock
    metaflow
    apprise
    ruff
    ty
commands =
    ruff check {posargs:.}
    ruff format --check {posargs:.}
    ty check metaflow_extensions/
    pytest tests/unit -v {posargs}
